//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheGamerR00M.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UsersPosts = new HashSet<UsersPost>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPass { get; set; }
        public int UserRankID { get; set; }
        public int UserStatusID { get; set; }
    
        public virtual AccountStatu AccountStatu { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual ICollection<UsersPost> UsersPosts { get; set; }
    }
}
